name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight, adjust as needed

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.4.0'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Generate variables.auto.tfvars'
      run: |
        IP_WHITELIST_VALUE="${{ secrets.IP_WHITELIST || '203.0.113.1/32' }}"
        echo "ip_whitelist = \"$IP_WHITELIST_VALUE\"" > variables.auto.tfvars
        echo "aws_access_key_id = \"${{ secrets.AWS_ACCESS_KEY_ID }}\"" >> variables.auto.tfvars
        echo "aws_secret_access_key = \"${{ secrets.AWS_SECRET_ACCESS_KEY }}\"" >> variables.auto.tfvars
        cat variables.auto.tfvars
        aws sts get-caller-identity

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
        cli_config_credentials_token: ${{ secrets.TFC_API_TOKEN }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy 

    - name: 'Terraform Apply Destroy'
      run: terraform apply -auto-approve
